name: genova_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3.*
  - r-essentials
  - bioconductor-rhdf5
  - r-remotes
  - r-devtools
  - libcurl
  - openssl
  - r-rcpp
  - r-data.table
  - r-igraph


